stages:
  - build
  - deploy

build_staging:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run type-check
    - npm run lint
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  except:
    - master
    - tags

build_site:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master
    - tags

deploy_staging:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync public/ s3://dev.jacknugent.io/ --delete
  environment:
    name: staging
    url: http://dev.jacknugent.io
  except:
   - master
   - tags

deploy_production:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync public/ s3://jacknugent.io/ --delete --recursive --cache-control max-age=31557600
    - aws cloudfront create-invalidation --distribution-id E2PCC8Q8LHLJMY --paths '/*' && aws cloudfront create-invalidation --distribution-id E1AB7TWPAABPC1 --paths '/*'
  environment:
    name: PROD
    url: http://jacknugent.io
  only:
    - master
